parameters:
#    ct_demo_hotel.example.class: CT\DemoHotelBundle\Example

services:
#    ct_demo_hotel.example:
#        class: %ct_demo_hotel.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
